# Generated by Django 5.0.6 on 2026-06-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadeddocument",
            name="cloudinary_url",
            field=models.URLField(
                blank=True, help_text="Cloudinary raw file URL", null=True
            ),
        ),
    ]
