# Generated by Django 5.0.6 on 2026-06-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_uploadeddocument_cloudinary_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadeddocument",
            name="faiss_index_url",
            field=models.URLField(
                blank=True, help_text="Cloudinary URL of FAISS index", null=True
            ),
        ),
        migrations.AddField(
            model_name="uploadeddocument",
            name="faiss_metadata_url",
            field=models.URLField(
                blank=True, help_text="Cloudinary URL of FAISS metadata", null=True
            ),
        ),
    ]
